# Generated by Django 3.1.7 on 2021-03-28 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_dependencia', models.CharField(max_length=200, verbose_name='Nombre')),
                ('abreviatura_dependencia', models.CharField(max_length=20, verbose_name='Abreviatura')),
                ('id_dep_tip', models.IntegerField(verbose_name='Id tipo')),
                ('id_sede', models.IntegerField(verbose_name='Id Sede')),
                ('id_depe_superior', models.IntegerField(verbose_name='Id Superior')),
                ('codigo_depe', models.CharField(max_length=8, verbose_name='Código')),
                ('estado_depe', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
                ('dias_laborables', models.IntegerField(verbose_name='Total de días laborable')),
                ('observacion', models.CharField(blank=True, max_length=100, verbose_name='Observación')),
                ('estado_periodo', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI')),
                ('apellido_paterno', models.CharField(blank=True, max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=200, verbose_name='Apellido materno')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('sexo', models.BooleanField()),
                ('fecha_nacimiento', models.DateField(blank=True, verbose_name='Fecha de nacimiento')),
                ('ubigeo_nacimiento', models.CharField(blank=True, max_length=6)),
                ('correo_institucional', models.CharField(blank=True, max_length=200, verbose_name='Correo institucional')),
                ('telefono', models.CharField(blank=True, max_length=9, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='tipoactividad',
            fields=[
                ('id_tipoactividad', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_tipoactividad', models.CharField(max_length=100, verbose_name='Nombre')),
                ('abreviatura_tipoactividad', models.CharField(max_length=20, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='jefe',
            fields=[
                ('id_jefe', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estado_jefe', models.BooleanField(blank=True, default=True)),
                ('fechahora_creacion', models.DateField(blank=True, default=datetime.datetime)),
                ('dni_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rf_persona_empleado', to='appcontrol.persona', verbose_name='Subordinado')),
                ('dni_jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rf_persona_jefe', to='appcontrol.persona', verbose_name='Jefe inmediato')),
            ],
        ),
     
    ]
